# Generated by Django 3.0.7 on 2020-08-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200816_1140'),
        ('users', '0004_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wish_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='wish_list', to='jobs.Job'),
        ),
    ]
